### 작성 확인
POST localhost:8080/api/board/post
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuIiwiYXV0aCI6eyJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9NRU1CRVIifV0sImRldGFpbHMiOm51bGwsImF1dGhlbnRpY2F0ZWQiOnRydWUsInByaW5jaXBhbCI6eyJwYXNzd29yZCI6bnVsbCwidXNlcm5hbWUiOiJuIiwiYXV0aG9yaXRpZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfTUVNQkVSIn1dLCJhY2NvdW50Tm9uRXhwaXJlZCI6dHJ1ZSwiYWNjb3VudE5vbkxvY2tlZCI6dHJ1ZSwiY3JlZGVudGlhbHNOb25FeHBpcmVkIjp0cnVlLCJlbmFibGVkIjp0cnVlLCJ1c2VySWQiOjF9LCJjcmVkZW50aWFscyI6bnVsbCwibmFtZSI6Im4ifSwidXNlcklkIjoxLCJpYXQiOjE3NDQ4ODUzNjksImV4cCI6MTc0NDkyODU2OX0.1Od8WcP5n0ba2Rb4Ffpy-RQXDSFEO123QUF0yM0mFNs"

{
  "title": "제목",
  "content": "내용"
}

### 작성 확인
GET localhost:8080/api/board/

