### 작성 확인
POST localhost:8080/api/board/
Content-Type: application/json
Authorization: Bearer {{acToken}}

{
  "title": "제22111ㄷㅂㅈㄷ1목",
  "content": "내2221ㅂㅈㄷㅂ111용"
}

### 작성 확인
GET localhost:8080/api/board/

### 특정 게시물 꺼내기
GET localhost:8080/api/board/3